### ISSUE TITLE
It sometimes changes math formulas

### ISSUE THREAD

**Issue by nickretallack** [zxbodya/flowts#4]
If I run `flowts` on a file containing this:
```
// @flow
export const x = g(2 * (n / 2) ** 0.5);
```
It converts it to this:
```
export const x = g(2 * (n / 2 ** 0.5));
```
This changes the formula.

If I use `--no-prettier`, I get this:
```
export const x = g(2 * (n / (2 ** 0.5)));
```
It has one extra parenthesis, and the logic is still changed in the same way.

If I use `--no-recast`, the code is unchanged besides the removal of the flow comment.

I discovered this after running `flowts` on a very large code base and manually inspecting all the results, so this problem is pretty rare.  However, it's a pretty scary problem to have.

If I remove the `export`, it fails fails verification like so:
```
// @flow
const x = g(2 * (n / (2 ** 0.5)));
```
```
verification failed, diff after stripping type annotations:
- Expected
+ Received

- const x = g(2 * (n / 2) ** 0.5);
+ const x = g(2 * (n / 2 ** 0.5));
```

**Comment by zxbodya** [comment]
Good catch, thanks for reporting.

Cause of it looks to be in recast, going to look into it.

There is a tradeoff about having it(that is why `--no-recast` is there) - babel by default does not preserve formatting, and by using recast it helps to keep formatting almost unchanged. And to be fair, for most of the cases - it works really well.

----

However, here is another issue about results verification, which is meant to verify that after removing flow/typescript annotations - the result is the same.

But because previously typescript was not supporting `import/export type` syntax - exports are not verified at the moment.

That should be easy to fix - going to look into it.

**Comment by zxbodya** [comment]
fixed in latest release
